# Generated by Django 3.2.3 on 2021-05-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('imei', models.CharField(max_length=30)),
                ('command_type', models.CharField(choices=[('1', 'Reboot'), ('2', 'Configure ip:port')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='command_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='COMMAND_RESPONSE', max_length=20)),
                ('response', models.CharField(choices=[('1', 'OK'), ('2', 'Failure')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('type', models.CharField(max_length=10)),
                ('imei', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video_upload_messege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=30)),
                ('video_data', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.CreateModel(
            name='Location_messege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('location_time', models.DateTimeField(auto_now=True, verbose_name='location-time')),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('imei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm_messege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('alarm_type', models.CharField(choices=[('1', 'VIBRATION'), ('2', 'OVERSPEED'), ('3', 'CRASH'), ('4', 'HARD_ACCELERATION'), ('5', 'HARD_BRAKE'), ('6', 'SHARP_TURN')], max_length=10)),
                ('alarm_time', models.DateTimeField(auto_now=True, verbose_name='alarm-time')),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('file_list', models.CharField(max_length=30)),
                ('imei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
