# Generated by Django 3.2.3 on 2021-05-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('video_data', models.CharField(max_length=30)),
                ('imei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.DeleteModel(
            name='Video_upload_messege',
        ),
        migrations.AddField(
            model_name='command_response',
            name='imei',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.AlterField(
            model_name='command_msg',
            name='imei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
    ]
